### PR TITLE
Use k8s version instead of replace in go.mod

### PR DESCRIPTION
**Pull request by LouisPlisso**
Now all k8s packages support "native" go module versions (kubernetes 1.16.7 maps to v0.16.7)

This allows for easy upgrades for patch versions and allows other packages to import this api easily

Note that the pinned version was 1.16.2: unfortunately this version did not provide native go module versions, so I bumped it to the latest in 1.16 which is 1.16.7

### CODE REVIEW

**Comment by LouisPlisso** [comment]
Note that I tested this change by building this repo (`go build ./...`) and also building operator-registry on top of this change (`go build ./...`)

**Comment by LouisPlisso** [comment]
@kevinrizza will you please merge and then create a release 0.1.1 so that I can base the other PRs on this tag (I'm currently testing on local forks, but it won't build if this is not publicly available)
Thanks!

**Comment by kevinrizza** [comment]
@LouisPlisso Sorry, didn't have a chance to test this before something else merged and now there's a conflict. Can you rebase and update the PR so I can test it before I merge?

Hopefully we can get some CI running against this repo sooner rather than later so we can be a little more automatic. Sorry about the trouble!

**Comment by LouisPlisso** [comment]
@kevinrizza now with the vendor directory included it's a huge PR
I've tested with go build ./... and go test ./...
and built operator-registry on top of this

don't know how to test more

**Comment by LouisPlisso** [comment]
@kevinrizza if you have time, could you please checkout this PR and run a `go mod vendor` to ensure the vendor directory is stable
it's the 1st time I work with a checked-in vendor, and with a 14k lines PR, it wouldn't hurt to double check 🙏 

thanks!

**Comment by ecordell** [comment]
```
$ git checkout -b LouisPlisso-pin_with_native_k8s_version_no_replace master
$ git pull https://github.com/LouisPlisso/api.git pin_with_native_k8s_version_no_replace
$ go mod vendor
$ go mod tidy
$ git status
On branch LouisPlisso-pin_with_native_k8s_version_no_replace
nothing to commit, working tree clean
$  go build -mod=vendor -o=v ./cmd/operator-verify/
```
/lgtm

**Pull request merged**
