### PR TITLE
Revert cleanup spec and status fields

### PR DESCRIPTION
**Pull request by hasbro17**
Reverts https://github.com/operator-framework/api/pull/100

The `spec.cleanup` and `status.cleanup` API fields are no longer needed since the [implementation](https://github.com/operator-framework/operator-lifecycle-manager/pull/2030) for the server-side operand deletion work is on hold and unlikely to proceed per the original enhancement proposal.

See: https://github.com/operator-framework/enhancements/pull/71/files

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by hasbro17** [comment]
Some concerns were raised over whether this is or isn't a breaking change. It technically is a breaking change that we would normally deprecate first. But given that there wasn't an implementation to accompany this API perhaps removing it outright would be easier.

**Comment by dinhxuanvu** [comment]
Is this cleanup field required? It doesn't appear so to me so it is not much of a breaking change as I thought it would be.

**Comment by anik120** [comment]
Closing this since it's stale now

**Pull request closed without merging**
