### PR TITLE
csv_validator: add check to ensure that the example is a valid JSON

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
csv_validator: add a check to ensure that the example is a valid JSON.
Note that when it fails we are pointing out where is the issue as well. 

**Motivation**
Closes: https://github.com/operator-framework/api/issues/116
Closes: https://github.com/operator-framework/api/pull/115

### CODE REVIEW

**Comment by camilamacedo86** [comment]
c/c @gallettilance @mvalarh @J0zi

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Comment by camilamacedo86** [comment]
@gallettilance could you give a hand with this one?

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
