### PR TITLE
:seedling: good practices validator nit clean up

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
- add warning test in the docs + clean up

### CODE REVIEW

**Comment by camilamacedo86** [comment]
c/c @ryantking

**Review by ryantking — APPROVED** [review]

**Comment by camilamacedo86** [comment]
@ryantking I think you have no permission to approve PRs here.
Could you lgtm this one?

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Pull request merged**
