### PR TITLE
Update modules to support k8s v0.29.2

### PR DESCRIPTION
**Pull request by Neo2308**
Add support for kubernetes v0.29.2 in the Operator Framework/api project dependencies.

Includes changes from https://github.com/operator-framework/api/pull/313

Helps with https://github.com/operator-framework/operator-sdk/issues/6651

### CODE REVIEW

**Comment by Neo2308** [comment]
@joelanford could you review this PR? Needs an approval for the workflows to run

**Comment by Neo2308** [comment]
@everettraven @gallettilance can you help with this?

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by everettraven** [comment]
@Neo2308 looks like this is failing a CI check

**Comment by Neo2308** [comment]
@everettraven I think it should be fixed now, need approval to run the tests again

**Comment by Neo2308** [comment]
@gallettilance  @joelanford @kevinrizza the checks have passed now, could you review?

cc: @everettraven

**Review by everettraven — APPROVED** [review]
Changes look good to me. I'm going to hold off on merging on a go ahead from @grokspawn and/or @tmshort as they have been orchestrating quite a few dependency bumps over the past few days across various operator-framework projects.

**Comment by everettraven** [comment]
I just spoke with @grokspawn and @tmshort in our community slack channel, and the consensus was that they would like to hold dependency bump PRs until they have a chance to take a look and can help orchestrate it amongst the many other dependabot and other bumps they have been doing. They mentioned likely not having cycles to take a look until next week at the earliest. Apologies for the delay, and many thanks for your understanding @Neo2308 !

**Comment by tmshort** [comment]
I'm going to look to see how bad this looks for OLM...

**Comment by grokspawn** [comment]
/approve

We're ready to coordinate OLMv0 repos' k8s bumps, now.  
Thank you so much for doing all the hard work here @Neo2308, and for your patience.

**Pull request merged**
