### PR TITLE
k8s 1.28 version update and go 1.20

### PR DESCRIPTION
**Pull request by acornett21**
- updating to k8s 1.28
- updating go to 1.20
- updating build GH go action to v4 and read from mod file
- Relates: operator-framework/operator-sdk#6554

### CODE REVIEW

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by perdasilva — APPROVED** [review]
lgtm

**Comment by Neo2308** [comment]
@perdasilva is this ready to merge now?
This is blocking progress on https://github.com/operator-framework/operator-sdk/issues/6554

**Comment by Neo2308** [comment]
@everettraven could you take a look at this PR?

**Comment by acornett21** [comment]
@joelanford @kevinrizza Would it be possible to get someone to review this PR? Thanks.

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by joelanford — APPROVED** [review]
/approve

**Comment by joelanford** [comment]
Oops. It looks like this PR reverted parts of #309.

I'll make a new PR to bump otelhttp again.

**Pull request merged**
