### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by timflannagan**
I'm looking into adding tide integration for this repository and wanted to comb over the current OWNERS file.

Remove Bowen's GH alias and add Joe and I's alias'.

### CODE REVIEW

**Comment by timflannagan** [comment]
I'd like to use this as a base case for when that openshift/release PR lands and tide has been enabled.

/hold

**Comment by timflannagan** [comment]
Alright, that tide release PR has merged. We likely need to wait until the new deployment has rolled out on the CI clusters before the tide checks starts showing up on all unmerged PRs.

/hold cancel

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
