### PR TITLE
modified the controller-runtime and controller-tools versions

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
Bumping controller-runtime and controller-tools version.

### CODE REVIEW

**Comment by varshaprasad96** [comment]
@laxmikantbpandhare can you change the commit message to bumping controller-runtime and controller-tools version specifically, k8s has already been updated to 1.22. Also, can you run `go mod tidy` and `make vendor`.

**Comment by laxmikantbpandhare** [comment]
> @laxmikantbpandhare can you change the commit message to bumping controller-runtime and controller-tools version specifically, k8s has already been updated to 1.22. Also, can you run `go mod tidy` and `make vendor`.

@varshaprasad96 I updated the commit message and also ran `make vendor`

**Pull request merged**
