### PR TITLE
Removing dependencies from olm and registry

### PR DESCRIPTION
**Pull request by Bowenislandsong**
This PR removes API dependency from OLM and Registry by copying necessary packages from them including:
olm/pkg/lib/version -> api/pkg/lib/version 
olm/pkg/api/apis/operators -> api/pkg/operators.
operator-registry/pkg/sqlite -> api/pkg/sqlite
operator-registry/pkg/registry -> api/pkg/registry
operator-registry/pkg/api -> api/pkg/registry/api
operator-registry/pkg/containertools -> api/pkg/registry/containertools
operator-registry/manifests -> api/test/data/manifests
operator-registry/bundles -> api/test/data/bundles
operator-registry/configmap.example.yaml -> api/test/data/configmap.example.yaml

This PR should be followed by 2 other PRs to remove packages mentioned above from OLM and registry so that only one set of them exist.

### CODE REVIEW

**Comment by njhale** [comment]
Thanks for working on this!

However, I do have some concerns around moving the API types. See [here](https://github.com/operator-framework/operator-lifecycle-manager/pull/1352#issuecomment-595241632) for details.

**Comment by dinhxuanvu** [comment]
This PR is obsolete.

**Pull request closed without merging**
