### PR TITLE
add current profile annotations to CVO manifests

### PR DESCRIPTION
**Pull request by guillaumerose**
This is matches openshift/enhancements#510 and doesn't change existing behavior

### CODE REVIEW

**Comment by guillaumerose** [comment]
/hold

I thought it would be better for https://github.com/operator-framework/operator-lifecycle-manager/pull/1832 but I can do it without this PR.

**Comment by guillaumerose** [comment]
not required finally.

**Comment by estroz** [comment]
This isn't the right place to be adding non-operator-framework annotations.

/hold

**Comment by estroz** [comment]
Actually this should probably be closed. I suggest making this PR to the downstream OLM repo (when it exists).

**Comment by guillaumerose** [comment]
Yes, can you PTAL at https://github.com/operator-framework/operator-lifecycle-manager/pull/1897 ? Thanks.

**Pull request closed without merging**
