### PR TITLE
fix: alm-example parse check should not fail when the annotation if empty

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
Fix error found using the check to test the images data.
Error `"Error: Value invalid character at 0\n \u003c--(see the invalid character): invalid example"` is faced when the alm-example is empty and should not.

Follow up: https://github.com/operator-framework/api/pull/207

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@dinhxuanvu, could you please give to us a hand on in this one?

**Comment by dinhxuanvu** [comment]
I'm a bit confused here. I only see a yaml file. Where are the codes?

**Comment by camilamacedo86** [comment]
Hi @dinhxuanvu, 

Sorry, I did not push the full commit. All done now.
Could you please help us get this small fix/nit get merged?

**Comment by dinhxuanvu** [comment]
@camilamacedo86 No worries. Can you do me a favor and strip the out anything that is not needed in the CSV yaml to reduce its size if possible.

**Comment by camilamacedo86** [comment]
@dinhxuanvu, done 👍

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
