### PR TITLE
:bug: fix ClusterServiceVersion CRD Generation

### PR DESCRIPTION
**Pull request by perdasilva**
New API updates is tripping up more validations against default values in the Deployment stanza of the CSV. This PR adds a couple of yq replacement queries to add default values to those fields.

seems the crds/zz_defs.go was also out of sync - regeneration seems to have fixed it

### CODE REVIEW

**Comment by perdasilva** [comment]
I think we can override the verify here. It seems like there's been a change in the go doc for json.RawMessage:

```
// RawMessage is a raw encoded JSON value.
// It implements [Marshaler] and [Unmarshaler] and can
// be used to delay JSON decoding or precompute a JSON encoding.
type RawMessage []byte
```
https://github.com/golang/go/blob/release-branch.go1.22/src/encoding/json/stream.go#L255

This is changing the field description and causing verify to fail

**Comment by perdasilva** [comment]
> It seems like `crds/zz_defs.go` needs `make format`

Thank you! I was chasing a different issue. Let's see if verify clears it (it will fail for the reasons I stated above in olm)...

**Review by m1kola — APPROVED** [review]

**Comment by m1kola** [comment]
/hold

One to check one thing before we merge

**Pull request merged**
